version: "3"

services:
    php_server:
        build: ./
        depends_on:
            - blat_server
            - mariadb_server
            - termlookup_server
        ports:
            - 80:80
        volumes:
            - ./:/var/www
        restart: always
    blat_server:
        build: ./go/blatserver
        volumes:
            - ./go/blatserver/assets:/assets
        restart: always
    mariadb_server:
        command:
            --group_concat_max_len=1024M
            --max_allowed_packet=1024M
            --plugin-load-add=server_audit.so
            --server_audit_file_path=/tmp
            --server_audit_events=query_dml_no_select
            --server_audit_file_rotate_now=1
            --server_audit_file_rotate_size=1000000000
            --innodb_buffer_pool_size=100M
            --net_read_timeout=3600
            --net_write_timeout=3600
            --connect_timeout=3600
            --interactive_timeout=86400
            --wait_timeout=86400
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - TZ=America/New_York
        image: mariadb:10.5
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
            - ./db/dumps:/docker-entrypoint-initdb.d
            - ./logs:/tmp
        restart: always
    termlookup_server:
        build: ./go/termlookupserver
        volumes:
            - ./go/termlookupserver/assets:/go/src/assets
        restart: always
